### ISSUE TITLE
在IE11、IE10和IE9中引用报错

### ISSUE THREAD

**Issue by Teiyanana** [forsigner/browser-md5-file#10]
在自己代码中引入browser-md5-file后报错，并不能执行。为了排除自己代码错误，使用官网案例在IE中打开也是报错的。

**Comment by ALongLi** [comment]
作者写的是es6的代码里面用的是class api，打包后的源码还是class，并没有转es5，所以直接在ie中直接就全军覆没了

**Comment by DDDenial** [comment]
> 作者写的是es6的代码里面用的是class api，打包后的源码还是class，并没有转es5，所以直接在ie中直接就全军覆没了

确实是这样的！

**Comment by hkdg** [comment]
自己使用babel转移
