### ISSUE TITLE
Getting Issue on progressFn. 

### ISSUE THREAD

**Issue by ammarmallik** [forsigner/browser-md5-file#3]
https://github.com/forsigner/browser-md5-file/blob/ff9923309b0b69636f29546db51bed30279c6148/src/index.js#L23

I have attached a few screenshots. This can be fixed by simply commenting this line. 

<img width="1243" alt="screenshot 2018-12-23 at 4 55 54 pm" src="https://user-images.githubusercontent.com/29196434/50383358-d43acc00-06d3-11e9-912e-19720a89f5f0.png">
<img width="803" alt="screenshot 2018-12-23 at 4 56 07 pm" src="https://user-images.githubusercontent.com/29196434/50383359-d43acc00-06d3-11e9-9bb5-09d8c4008ab0.png">

Thanks. :)

**Comment by forsigner** [comment]
fixed in  `browser-md5-file@1.1.1`
